### ISSUE TITLE
liquibase: Waiting for changelog lock....

### ISSUE THREAD

**Issue by bugcy013** [opennms-forge/docker-horizon-core-web#42]
Hi Guys,

When I try to start `docker-compose up` I am getting an error. can you please guide me How to fix this.

```
:~/docker-horizon-core-web$ docker-compose up
Starting opennms.psql ... done
Starting opennms.hzn.core.web ... done
Attaching to opennms.psql, opennms.hzn.core.web
opennms.psql | 2018-10-12 01:25:33.279 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
opennms.psql | 2018-10-12 01:25:33.280 CEST [1] LOG:  listening on IPv6 address "::", port 5432
opennms.hzn.core.web | Initialize database and Karaf configuration and do install or upgrade the database schema.
opennms.psql | 2018-10-12 01:25:33.330 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
opennms.hzn.core.web | runjava: Looking for an appropriate JRE...
opennms.hzn.core.web | runjava: Checking for an appropriate JRE in JAVA_HOME...
opennms.psql | 2018-10-12 01:25:33.415 CEST [23] LOG:  database system was shut down at 2018-10-12 01:21:04 CEST
opennms.psql | 2018-10-12 01:25:33.503 CEST [1] LOG:  database system is ready to accept connections
opennms.hzn.core.web | runjava: found: "/usr/lib/jvm/java/bin/java" is an appropriate JRE
opennms.hzn.core.web | runjava: value of "/usr/lib/jvm/java/bin/java" stored in configuration file
opennms.hzn.core.web | ==============================================================================
opennms.hzn.core.web | OpenNMS Installer
opennms.hzn.core.web | ==============================================================================
opennms.hzn.core.web | 
opennms.hzn.core.web | Configures PostgreSQL tables, users, and other miscellaneous settings.
opennms.hzn.core.web | 
opennms.hzn.core.web | DEBUG: Platform is IPv6 ready: true
opennms.hzn.core.web | - searching for libjicmp.so:
opennms.hzn.core.web |   - trying to load /usr/lib64/libjicmp.so: OK
opennms.hzn.core.web | - searching for libjicmp6.so:
opennms.hzn.core.web |   - trying to load /usr/lib64/libjicmp6.so: OK
opennms.hzn.core.web | - searching for libjrrd.so:
opennms.hzn.core.web |   - trying to load /usr/lib64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/opennms/lib/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/opennms/lib/linux64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/java/packages/lib/amd64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /lib64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /lib/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib/jni/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/lib/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /usr/local/lib/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/NMSjicmp/lib/32/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/NMSjicmp/lib/64/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/NMSjicmp6/lib/32/libjrrd.so: NO
opennms.hzn.core.web |   - trying to load /opt/NMSjicmp6/lib/64/libjrrd.so: NO
opennms.hzn.core.web | - Failed to load the optional jrrd library.
opennms.hzn.core.web |   - This error is not fatal, since jrrd is only required for optional features.
opennms.hzn.core.web |   - For more information, see http://www.opennms.org/index.php/jrrd
opennms.hzn.core.web | - searching for libjrrd2.so:
opennms.hzn.core.web |   - trying to load /usr/lib64/libjrrd2.so: OK
opennms.hzn.core.web | 01:26:07.171 [Main] WARN  org.opennms.install.Installer - Could not create file: /opt/opennms/etc/libraries.properties
opennms.hzn.core.web | - using SQL directory... /opt/opennms/etc
opennms.hzn.core.web | - using create.sql... /opt/opennms/etc/create.sql
opennms.hzn.core.web | 01:26:07.182 [Main] INFO  org.opennms.core.schema.Migrator - validating database version
opennms.hzn.core.web | * using 'postgres' as the PostgreSQL user for OpenNMS
opennms.hzn.core.web | * using 'opennms' as the PostgreSQL database name for OpenNMS
opennms.hzn.core.web | 01:26:07.291 [Main] INFO  org.opennms.core.schema.Migrator - validating database version
opennms.hzn.core.web | 01:26:07.302 [Main] INFO  org.opennms.core.schema.Migrator - adding PL/PgSQL support to the database, if necessary
opennms.hzn.core.web | 01:26:07.308 [Main] INFO  org.opennms.core.schema.Migrator - PL/PgSQL call handler exists
opennms.hzn.core.web | 01:26:07.309 [Main] INFO  org.opennms.core.schema.Migrator - PL/PgSQL language exists
opennms.hzn.core.web | - checking if database "opennms" is unicode... ALREADY UNICODE
opennms.hzn.core.web | - checking if time of database "opennms" is matching system time... OK
opennms.hzn.core.web | - Checking for old import files in /opt/opennms/etc... DONE
opennms.hzn.core.web | - Running migration for changelog: URL [jar:file:/opt/opennms/lib/org.opennms.core.schema-23.0.0-SNAPSHOT-liquibase.jar!/changelog.xml]
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:26 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:27 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:28 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:29 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | INFO 10/12/18 1:30 AM:liquibase: Waiting for changelog lock....
opennms.hzn.core.web | java.lang.reflect.InvocationTargetException
opennms.hzn.core.web | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
opennms.hzn.core.web | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
opennms.hzn.core.web | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
opennms.hzn.core.web | 	at java.lang.reflect.Method.invoke(Method.java:498)
opennms.hzn.core.web | 	at org.opennms.bootstrap.Bootstrap$4.run(Bootstrap.java:525)
opennms.hzn.core.web | 	at java.lang.Thread.run(Thread.java:748)
opennms.hzn.core.web | Caused by: org.opennms.core.schema.MigrationException: unable to migrate the database
opennms.hzn.core.web | 	at org.opennms.core.schema.Migrator.migrate(Migrator.java:479)
opennms.hzn.core.web | 	at org.opennms.install.Installer.install(Installer.java:275)
opennms.hzn.core.web | 	at org.opennms.install.Installer.main(Installer.java:991)
opennms.hzn.core.web | 	... 6 more
opennms.hzn.core.web | Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fe80:0:0:0:42:acff:fe15:3%eth0 (fe80:0:0:0:42:acff:fe15:3%eth0) since 10/12/18 1:17 AM
opennms.hzn.core.web | 	at liquibase.lockservice.LockService.waitForLock(LockService.java:81)
opennms.hzn.core.web | 	at liquibase.Liquibase.update(Liquibase.java:102)
opennms.hzn.core.web | 	at org.opennms.core.schema.Migrator.migrate(Migrator.java:477)
opennms.hzn.core.web | 	... 8 more
opennms.hzn.core.web exited with code 127

```

**Comment by indigo423** [comment]
I've tried the following to reproduce the problem:

```
https://github.com/opennms-forge/docker-horizon-core-web.git
cd docker-horizon-core-web
docker-compose up -d
```

After waiting for startup the service stack was started correctly:

```
docker-compose ps                                                                                                                                    ✔  7658  13:28:00
        Name                      Command                 State                                                                       Ports
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
opennms.hzn.core.web   /docker-entrypoint.sh -s        Up (healthy)   1099/tcp, 0.0.0.0:162->162/udp, 18980/tcp, 514/udp, 5817/tcp, 0.0.0.0:61616->61616/tcp, 0.0.0.0:8101->8101/tcp, 0.0.0.0:8980->8980/tcp
opennms.psql           docker-entrypoint.sh postgres   Up (healthy)   0.0.0.0:5432->5432/tcp
```

Be aware when you run out of master branch you start the bleeding release of Horizon which is 24.0.0-SNAPSHOT.
